version: "3.8"

services:
  bank-api:
    build:
      context: BankAPI
      dockerfile: Dockerfile
    container_name: bank_api
    restart: unless-stopped
    command: bash -c "npm run start:prod"
    environment:
      DATABASE_URL: postgres://postgres:4AAF4cv-XIMKPPE12c-izplKT51HMr_e@db:5432/bank_db
      JWT_SECRET: super-secret
    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - default-network

  bank-ui:
    build:
      context: PortfolioWebsite
      dockerfile: Dockerfile
    container_name: bank_ui
    restart: unless-stopped
    command: bash -c "npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - bank-api
    networks:
      - default-network

  db:
    image: postgres
    restart: always
    # command: bash -c "npx prisma migrate prod --name init"
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4AAF4cv-XIMKPPE12c-izplKT51HMr_e
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    networks:
      - default-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5050:80"

volumes:
  db:

networks:
  default-network:
    driver: bridge
